GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Baraka",
    "email": "baraka@mortalcommbat.com",
    "gender": "Male"
}

###
PATCH http://localhost:3000/users/5
Content-Type: application/json

{
    "name": "Rayden",
    "email": "lightrayden@mortalcommbat.com",
    "gender": "Male"
}

###
DELETE http://localhost:3000/users/6